### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by justinchuby** [rominf/module-wrapper#2]
It seems like importing the package in Python 3.10.1 will raise

```
FileNotFoundError: [Errno 2] No such file or directory: '/.../python3.10/site-packages/stdlib_list/lists/3.10.txt'
```

**Comment by rominf** [comment]
Hi. Sorry for the very, very long delay. I've put the library into maintenance mode (see reasons and proper ways to do similar things in README.md). `stdlib_list` doesn't support Python 3.10, and fixing the library is not trivial task, especially without proper testing.
